allowBuilds:
  core-js-pure: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@vitest/browser-playwright@4.1.9'
  - '@vitest/browser@4.1.9'
  - '@vitest/expect@4.1.9'
  - '@vitest/mocker@4.1.9'
  - '@vitest/pretty-format@4.1.9'
  - '@vitest/runner@4.1.9'
  - '@vitest/snapshot@4.1.9'
  - '@vitest/spy@4.1.9'
  - '@vitest/utils@4.1.9'
  - '@volverjs/style@0.1.24'
  - playwright-core@1.61.0
  - playwright@1.61.0
  - vitest@4.1.9
  - '@vue/compiler-core@3.5.39'
  - '@vue/compiler-dom@3.5.39'
  - '@vue/compiler-sfc@3.5.39'
  - '@vue/compiler-ssr@3.5.39'
  - '@vue/reactivity@3.5.39'
  - '@vue/runtime-core@3.5.39'
  - '@vue/runtime-dom@3.5.39'
  - '@vue/server-renderer@3.5.39'
  - '@vue/shared@3.5.39'
  - vue@3.5.39
