allowBuilds:
  core-js-pure: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@volverjs/ui-vue@0.0.22'
  - '@vue/compiler-core@3.5.43'
  - '@vue/compiler-dom@3.5.43'
  - '@vue/compiler-sfc@3.5.43'
  - '@vue/compiler-ssr@3.5.43'
  - '@vue/reactivity@3.5.43'
  - '@vue/runtime-core@3.5.43'
  - '@vue/runtime-dom@3.5.43'
  - '@vue/server-renderer@3.5.43'
  - '@vue/shared@3.5.43'
  - vue@3.5.43
  - zod@4.6.5
