name: Main pipeline

on:
    # Runs on release publish
    release:
        types: [published]

jobs:
    # build
    build:
        uses: ./.github/workflows/build.yml

    test:
        needs: build
        uses: ./.github/workflows/test.yml

    publish:
        needs: test
        uses: ./.github/workflows/publish.yml
        with:
            npm-token: ${{secrets.NPM_TOKEN}}
